Análisis de ventas de una empresa de electrodomésticos

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df=pd.read_excel('ventas_electrodomesticos_integrador.xlsx', sheet_name='Ventas')

In [3]:
# Primeras filas del dataset
df.head()

,ID_Venta,Fecha,Sucursal,Ciudad,Canal,Vendedor,Categoria,Producto,Marca,Cantidad,Precio_Unitario,Descuento_Porc,Medio_Pago,Tipo_Cliente,Costo_Envio,Estado_Venta,Calificacion
0,V001,2026-08-01,Centro,CABA,Presencial,Lucía Gómez,Heladeras,Heladera 320L,FríoMax,1,780000,0.10,Tarjeta crédito,Particular,0,Entregada,5.0
1,V002,2026-08-01,Norte,San Isidro,Online,Martín López,Televisores,Smart TV 50,Visión,1,620000,0.05,Tarjeta crédito,Particular,18000,Entregada,4.0
2,V003,2026-08-02,Oeste,Morón,Presencial,Carla Ruiz,Pequeños electro,Microondas 28L,HogarPlus,2,185000,0.00,Débito,Particular,0,Entregada,4.0
3,V004,2026-08-02,Centro,CABA,Online,Diego Fernández,Lavarropas,Lavarropas 8kg,AquaWash,1,690000,0.12,Transferencia,Particular,22000,Entregada,5.0
4,V005,2026-08-03,Sur,Quilmes,Presencial,Sofía Pérez,Climatización,Aire acondicionado 3000F,ClimaAR,1,540000,0.08,Tarjeta crédito,Particular,0,Entregada,4.0

In [4]:
# Dimensiones: filas (registros) y columnas (variables)
df.shape

(36, 17)

In [5]:
# Nombres de las columnas
df.columns

Index(['ID_Venta', 'Fecha', 'Sucursal', 'Ciudad', 'Canal', 'Vendedor',
       'Categoria', 'Producto', 'Marca', 'Cantidad', 'Precio_Unitario',
       'Descuento_Porc', 'Medio_Pago', 'Tipo_Cliente', 'Costo_Envio',
       'Estado_Venta', 'Calificacion'],
      dtype='str')

In [6]:
# Tipos de datos detectados por Pandas
df.dtypes

ID_Venta                      str
Fecha              datetime64[us]
Sucursal                      str
Ciudad                        str
Canal                         str
Vendedor                      str
Categoria                     str
Producto                      str
Marca                         str
Cantidad                    int64
Precio_Unitario             int64
Descuento_Porc            float64
Medio_Pago                    str
Tipo_Cliente                  str
Costo_Envio                 int64
Estado_Venta                  str
Calificacion              float64
dtype: object

In [7]:
# Resumen de valores no nulos y tipos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 36 entries, 0 to 35
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID_Venta         36 non-null     str
 1   Fecha            36 non-null     datetime64[us]
 2   Sucursal         36 non-null     str
 3   Ciudad           36 non-null     str
 4   Canal            36 non-null     str
 5   Vendedor         36 non-null     str
 6   Categoria        36 non-null     str
 7   Producto         36 non-null     str
 8   Marca            36 non-null     str
 9   Cantidad         36 non-null     int64
 10  Precio_Unitario  36 non-null     int64
 11  Descuento_Porc   35 non-null     float64
 12  Medio_Pago       35 non-null     str
 13  Tipo_Cliente     36 non-null     str
 14  Costo_Envio      36 non-null     int64
 15  Estado_Venta     36 non-null     str
 16  Calificacion     34 non-null     float64
dtypes: datetime64[us](1), float64(2), int64(3), str(11)
memory usage: 8.5 KB

In [8]:
# Estadísticas descriptivas de las columnas numéricas
df.describe()

,Fecha,Cantidad,Precio_Unitario,Descuento_Porc,Costo_Envio,Calificacion
count,36,36.000000,3.600000e+01,35.000000,36.000000,34.000000
mean,2026-08-09 12:00:00,1.305556,4.781389e+05,0.076286,10833.333333,4.294118
min,2026-08-01 00:00:00,1.000000,5.200000e+04,0.000000,0.000000,3.000000
25%,2026-08-05 00:00:00,1.000000,1.825000e+05,0.050000,0.000000,4.000000
50%,2026-08-09 12:00:00,1.000000,4.575000e+05,0.070000,8500.000000,4.000000
75%,2026-08-14 00:00:00,1.000000,6.950000e+05,0.100000,20500.000000,5.000000
max,2026-08-18 00:00:00,4.000000,1.450000e+06,0.200000,38000.000000,5.000000
std,NaN,0.668450,3.574149e+05,0.051283,11910.379627,0.629064

•	¿Cuántos registros contiene el archivo?
    contiene 36 registros 
•	¿Cuántas variables posee?
    posee 17 variables 
•	¿Qué variables son numéricas?
    - Cantidad (entera/discreta).
    - Precio_Unitario (entera/continua en pesos).
    - Descuento_Porc (decimal/porcentaje).
    - Costo_Envio (entera en pesos).
    - Calificacion (decimal/escala de 1 a 5).
•	¿Qué variables son categóricas?
    Identificador: ID_Venta.
    Cualitativas/Texto: Sucursal, Ciudad, Canal, Vendedor, Categoria, Producto, Marca, Medio_Pago, Tipo_Cliente y Estado_Venta.
    (Nota técnica: Fecha es de tipo temporal / datetime).
•	¿Qué información representa cada fila?
    Cada fila representa una transacción individual de venta de un producto específico, detallando el cliente, vendedor, canal, costos asociados, estado de entrega y calificación del servicio.

In [9]:
# Ver cuántos valores faltan en cada columna
print(df.isnull().sum())

ID_Venta           0
Fecha              0
Sucursal           0
Ciudad             0
Canal              0
Vendedor           0
Categoria          0
Producto           0
Marca              0
Cantidad           0
Precio_Unitario    0
Descuento_Porc     1
Medio_Pago         1
Tipo_Cliente       0
Costo_Envio        0
Estado_Venta       0
Calificacion       2
dtype: int64

In [10]:
# Ver si hay filas enteras duplicadas
print(df.duplicated().sum())

0